### ISSUE TITLE
muffinmar.io offline? :-(

### ISSUE THREAD

**Issue by wallsingham** [MuffinMario/Siedler-4-Script-und-Referenzen#2]
Hallo Mario,

ich wollte gerade dein Tool für Custom Widescreen nutzen und sehe dass deine Seite nicht erreichbar ist. Ich fand das tool aber so genial dass ich es zu schade finde wenn es einfach verschwindet. Kommt die Seite wieder? bzw. wird das Tool wieder benutzbar sein? (https://s4.muffinmar.io/downloads/downloadRequest.php?file=3&width=3840&height=2160).

Viele Grüße
Hektor

**Comment by wallsingham** [comment]
Es hat nun funktioniert. Vielen Dank @MuffinMario 
Ich schliesse hier

**Comment by MuffinMario** [comment]
Tut mir leid, habe keine Benachrichtigung für das Issue bekommen 😓 
Ich habe bzw, hatte Probleme mit dem Hoster in dem ein Hostersystem Probleme gemacht hatte, auf meinem Discord habe ich das auch geschrieben. Die Website ist jetzt wieder online, jedoch gibt es keine Datenbank mehr und da muss ich mich noch mal dran setzen :)
LG
