### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by domhel** [MuffinMario/Siedler-4-Script-und-Referenzen#3]
Hey,
hat nichts mit dem Repo zu tun, aber deine Webseite ist down?
Gibt es eine andere mit all den S4 Infos?

**Comment by MuffinMario** [comment]
Sorry späte Antwort. Website geht wieder. Alternativ kann ich nur https://docs.settlers-united.com/v/s4-lua-api-de/tutorials/readme empfehlen. Ist mMn übersichtlicher :)
LG
